apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: test-server
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: test-server
status:
  loadBalancer: {}
---
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test-server
  name: test-server
spec:
  containers:
  - image: test-server:v1
    name: test-server
    ports:
    - containerPort: 8080
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
